-- ============================================================================
-- FlowWise — Migration 007: procurement & intelligence (Phase 3).
--
-- Reorder rules, an explainable reorder-suggestion evaluator, purchase orders
-- (draft → sent → partially_received → received), partial receipts wired into
-- the existing GRN path, a supplier scorecard view, and signed outbound
-- webhooks for PO events.
--
-- Invariant 3 holds here too: converting a suggestion into a PO commits the
-- suggestion status flip + PO rows in ONE transaction, and a GRN receipt
-- commits the ledger movements + PO received-quantity update in ONE
-- transaction (never a receipt without its stock movement, and vice versa).
-- Invariant 4: POs carry client_operation_id (unique per org); replaying the
-- create returns the stored PO with zero side effects.
-- ============================================================================

-- ---- Reorder rules (per branch + variant) ----------------------------------
CREATE TABLE reorder_rules (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id             uuid NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  branch_id          uuid NOT NULL REFERENCES branches(id),
  variant_id         uuid NOT NULL REFERENCES product_variants(id),
  reorder_point      numeric(14,4) NOT NULL CHECK (reorder_point >= 0),
  reorder_quantity   numeric(14,4) NOT NULL CHECK (reorder_quantity > 0),
  lead_time_days     int NOT NULL DEFAULT 0 CHECK (lead_time_days >= 0),
  safety_stock_days  int NOT NULL DEFAULT 0 CHECK (safety_stock_days >= 0),
  demand_window_days int NOT NULL DEFAULT 30 CHECK (demand_window_days BETWEEN 1 AND 365),
  is_active          boolean NOT NULL DEFAULT true,
  created_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, branch_id, variant_id)
);
CREATE INDEX idx_reorder_rules_branch ON reorder_rules (org_id, branch_id);

-- ---- Purchase orders -------------------------------------------------------
CREATE TYPE po_status AS ENUM ('draft', 'sent', 'partially_received', 'received', 'cancelled');

CREATE TABLE purchase_orders (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id              uuid NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  branch_id           uuid NOT NULL REFERENCES branches(id),
  supplier_id         uuid NOT NULL REFERENCES suppliers(id),
  document_no         text NOT NULL,
  status              po_status NOT NULL DEFAULT 'draft',
  client_operation_id text NOT NULL,                    -- Invariant 4
  expected_delivery   date,
  notes               text,
  created_by_user_id  uuid REFERENCES users(id) ON DELETE SET NULL,
  created_by_device_id uuid REFERENCES devices(id) ON DELETE SET NULL,
  sent_at             timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, client_operation_id),
  UNIQUE (org_id, document_no)
);
CREATE INDEX idx_pos_branch_time ON purchase_orders (org_id, branch_id, created_at DESC);
CREATE INDEX idx_pos_supplier    ON purchase_orders (org_id, supplier_id);

-- unit_cost is SNAPSHOTTED at order time; received_quantity tracks receipts.
CREATE TABLE purchase_order_lines (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id            uuid NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  purchase_order_id uuid NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  line_no           int  NOT NULL CHECK (line_no > 0),
  variant_id        uuid NOT NULL REFERENCES product_variants(id),
  quantity          numeric(14,4) NOT NULL CHECK (quantity > 0),
  unit_cost         numeric(14,4) NOT NULL CHECK (unit_cost >= 0),
  received_quantity numeric(14,4) NOT NULL DEFAULT 0 CHECK (received_quantity >= 0),
  UNIQUE (org_id, purchase_order_id, line_no),
  UNIQUE (org_id, purchase_order_id, variant_id)
);
CREATE INDEX idx_po_lines_po ON purchase_order_lines (org_id, purchase_order_id);

-- ---- Reorder suggestions (explainable, generated by the evaluator) --------
CREATE TYPE suggestion_status AS ENUM ('open', 'converted', 'dismissed');

CREATE TABLE reorder_suggestions (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id               uuid NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  branch_id            uuid NOT NULL REFERENCES branches(id),
  variant_id           uuid NOT NULL REFERENCES product_variants(id),
  status               suggestion_status NOT NULL DEFAULT 'open',
  current_stock        numeric(14,4) NOT NULL,
  reorder_point        numeric(14,4) NOT NULL,
  avg_daily_demand     numeric(14,4) CHECK (avg_daily_demand IS NULL OR avg_daily_demand >= 0),
  lead_time_days       int NOT NULL DEFAULT 0,
  safety_stock_days    int NOT NULL DEFAULT 0,
  days_of_cover        numeric(14,4) CHECK (days_of_cover IS NULL OR days_of_cover >= 0),
  suggested_quantity   numeric(14,4) NOT NULL CHECK (suggested_quantity > 0),
  unit_cost            numeric(14,4) CHECK (unit_cost IS NULL OR unit_cost >= 0),
  suggested_supplier_id uuid REFERENCES suppliers(id) ON DELETE SET NULL,
  reason               text NOT NULL,
  converted_po_id      uuid REFERENCES purchase_orders(id) ON DELETE SET NULL,
  generated_at         timestamptz NOT NULL DEFAULT now(),
  created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_suggestions_branch ON reorder_suggestions (org_id, branch_id, status);
-- At most one OPEN suggestion per item — re-running the evaluator refreshes it.
CREATE UNIQUE INDEX uq_suggestions_open
  ON reorder_suggestions (org_id, branch_id, variant_id) WHERE status = 'open';

-- ---- GRNs may now fulfil a PO (partial receipts) ---------------------------
ALTER TABLE goods_receipts ADD COLUMN po_id uuid REFERENCES purchase_orders(id) ON DELETE SET NULL;
CREATE INDEX idx_grns_po ON goods_receipts (org_id, po_id);

-- A GRN line against a PO must (a) be a line that exists on the PO and
-- (b) not push received past ordered. FK checks bypass RLS, so the lookup
-- runs as the invoker → RLS hides cross-org rows and the guard errors.
CREATE FUNCTION assert_po_receipt_within_ordered() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  v_po_id    uuid;
  v_ordered  numeric(14,4);
  v_received numeric(14,4);
BEGIN
  SELECT g.po_id INTO v_po_id FROM goods_receipts g WHERE g.id = NEW.goods_receipt_id;
  IF v_po_id IS NULL THEN
    RETURN NEW;
  END IF;
  SELECT quantity, received_quantity INTO v_ordered, v_received
  FROM purchase_order_lines pl
  WHERE pl.purchase_order_id = v_po_id AND pl.variant_id = NEW.variant_id;
  IF v_ordered IS NULL THEN
    RAISE EXCEPTION 'variant % is not a line on purchase order %', NEW.variant_id, v_po_id
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  IF v_received + NEW.quantity > v_ordered THEN
    RAISE EXCEPTION 'receipt of % exceeds the % ordered on purchase order % (already received %)',
      NEW.quantity, v_ordered, v_po_id, v_received
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  RETURN NEW;
END
$$;

CREATE TRIGGER trg_grn_lines_po_limit
  BEFORE INSERT ON goods_receipt_lines
  FOR EACH ROW EXECUTE FUNCTION assert_po_receipt_within_ordered();

-- ---- PO lifecycle immutability --------------------------------------------
-- drafts → sent/cancelled; sent/partially_received → receipt progress only;
-- received/cancelled are terminal and immutable (mirrors Invariant 5 for
-- completed documents — corrections are NEW documents, never edits).
CREATE FUNCTION protect_po_document() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.status <> 'draft' THEN
      RAISE EXCEPTION 'non-draft purchase orders are immutable: DELETE forbidden'
        USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN OLD; -- a draft PO may be deleted; it has no ledger effect yet
  END IF;

  IF OLD.status IN ('received', 'cancelled') THEN
    RAISE EXCEPTION 'received/cancelled purchase orders are immutable: % forbidden', TG_OP
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;

  -- sent / partially_received: only the status column may change.
  IF OLD.status IN ('sent', 'partially_received') THEN
    IF NEW.org_id <> OLD.org_id OR NEW.branch_id <> OLD.branch_id
       OR NEW.supplier_id <> OLD.supplier_id OR NEW.document_no <> OLD.document_no
       OR NEW.client_operation_id <> OLD.client_operation_id
       OR NEW.notes IS DISTINCT FROM OLD.notes
       OR NEW.expected_delivery IS DISTINCT FROM OLD.expected_delivery THEN
      RAISE EXCEPTION 'sent purchase orders are immutable: only status may change'
        USING ERRCODE = 'integrity_constraint_violation';
    END IF;
  END IF;
  RETURN NEW;
END
$$;

CREATE TRIGGER trg_pos_protect
  BEFORE UPDATE OR DELETE ON purchase_orders
  FOR EACH ROW EXECUTE FUNCTION protect_po_document();

-- Org-consistency guards for new FKs (same rationale as assert_batch_in_org).
CREATE FUNCTION assert_variant_in_org() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM product_variants v WHERE v.id = NEW.variant_id AND v.org_id = NEW.org_id) THEN
    RAISE EXCEPTION 'variant does not belong to this organisation'
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  RETURN NEW;
END
$$;

CREATE FUNCTION assert_po_in_org() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM purchase_orders po WHERE po.id = NEW.purchase_order_id AND po.org_id = NEW.org_id) THEN
    RAISE EXCEPTION 'purchase order does not belong to this organisation'
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  RETURN NEW;
END
$$;

CREATE FUNCTION assert_supplier_in_org() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM suppliers s WHERE s.id = NEW.supplier_id AND s.org_id = NEW.org_id) THEN
    RAISE EXCEPTION 'supplier does not belong to this organisation'
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  RETURN NEW;
END
$$;

CREATE TRIGGER trg_po_lines_variant_org
  BEFORE INSERT OR UPDATE OF variant_id ON purchase_order_lines
  FOR EACH ROW EXECUTE FUNCTION assert_variant_in_org();
CREATE TRIGGER trg_po_lines_po_org
  BEFORE INSERT OR UPDATE OF purchase_order_id ON purchase_order_lines
  FOR EACH ROW EXECUTE FUNCTION assert_po_in_org();
CREATE TRIGGER trg_po_supplier_org
  BEFORE INSERT OR UPDATE OF supplier_id ON purchase_orders
  FOR EACH ROW EXECUTE FUNCTION assert_supplier_in_org();
CREATE TRIGGER trg_rules_variant_org
  BEFORE INSERT OR UPDATE OF variant_id ON reorder_rules
  FOR EACH ROW EXECUTE FUNCTION assert_variant_in_org();
CREATE TRIGGER trg_suggestions_variant_org
  BEFORE INSERT OR UPDATE OF variant_id ON reorder_suggestions
  FOR EACH ROW EXECUTE FUNCTION assert_variant_in_org();

-- ---- Outbound webhooks -----------------------------------------------------
CREATE TABLE webhooks (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id            uuid NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  url               text NOT NULL,
  secret            text NOT NULL,          -- HMAC signing secret (server-generated)
  events            jsonb NOT NULL DEFAULT '["po.*"]'::jsonb,
  is_active         boolean NOT NULL DEFAULT true,
  created_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_webhooks_org ON webhooks (org_id);

CREATE TYPE webhook_delivery_status AS ENUM ('pending', 'success', 'failed');

CREATE TABLE webhook_deliveries (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id          uuid NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  webhook_id      uuid NOT NULL REFERENCES webhooks(id) ON DELETE CASCADE,
  event           text NOT NULL,
  payload         jsonb NOT NULL,
  signature       text NOT NULL,
  status          webhook_delivery_status NOT NULL DEFAULT 'pending',
  attempts        int NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  last_http_status int,
  last_error      text,
  -- NULL on terminal rows (success/failed): no retry scheduled.
  next_attempt_at timestamptz DEFAULT now(),
  delivered_at    timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_webhook_deliveries_pending ON webhook_deliveries (org_id, status, next_attempt_at);

-- ---- Supplier scorecard (derived, never stored) ----------------------------
-- Per-PO metrics are aggregated in LATERAL subqueries so a PO with several
-- GRNs (split deliveries) never double-counts its line values.
CREATE VIEW v_supplier_scorecard
WITH (security_invoker = true) AS
WITH po_metrics AS (
  SELECT po.supplier_id, po.org_id,
         COUNT(*) FILTER (WHERE po.status <> 'draft')::int AS po_count,
         COUNT(*) FILTER (WHERE po.status = 'received')::int AS fully_received_count,
         COUNT(*) FILTER (WHERE po.status IN ('partially_received', 'received'))::int AS partially_or_fully_received_count,
         COALESCE(SUM(plv.value), 0)::numeric(14,4) AS total_ordered_value,
         COALESCE(SUM(glv.value), 0)::numeric(14,4) AS total_received_value,
         AVG(EXTRACT(EPOCH FROM (gr.first_received_at - po.sent_at)) / 86400.0) AS avg_lead_time_days,
         COUNT(*) FILTER (WHERE po.expected_delivery IS NOT NULL
                            AND po.status IN ('partially_received', 'received')
                            AND gr.first_received_at::date <= po.expected_delivery)::int AS on_time_count,
         COUNT(*) FILTER (WHERE po.expected_delivery IS NOT NULL
                            AND po.status IN ('partially_received', 'received'))::int AS due_count
  FROM purchase_orders po
  LEFT JOIN LATERAL (
    SELECT MIN(g.received_at) AS first_received_at
    FROM goods_receipts g
    WHERE g.po_id = po.id
  ) gr ON true
  LEFT JOIN LATERAL (
    SELECT SUM(pl.quantity * pl.unit_cost) AS value
    FROM purchase_order_lines pl
    WHERE pl.purchase_order_id = po.id
  ) plv ON true
  LEFT JOIN LATERAL (
    SELECT SUM(gl.quantity * gl.unit_cost) AS value
    FROM goods_receipts g
    JOIN goods_receipt_lines gl ON gl.goods_receipt_id = g.id
    WHERE g.po_id = po.id
  ) glv ON true
  GROUP BY po.supplier_id, po.org_id
)
SELECT s.id AS supplier_id, s.name AS supplier_name, s.code AS supplier_code,
       COALESCE(pm.po_count, 0)::int AS po_count,
       COALESCE(pm.fully_received_count, 0)::int AS fully_received_count,
       COALESCE(pm.partially_or_fully_received_count, 0)::int AS partially_or_fully_received_count,
       COALESCE(pm.total_ordered_value, 0)::numeric(14,4) AS total_ordered_value,
       COALESCE(pm.total_received_value, 0)::numeric(14,4) AS total_received_value,
       ROUND(pm.avg_lead_time_days::numeric, 1) AS avg_lead_time_days,
       CASE WHEN COALESCE(pm.due_count, 0) = 0 THEN NULL
            ELSE ROUND((pm.on_time_count::numeric / pm.due_count), 2)
       END AS on_time_rate
FROM suppliers s
LEFT JOIN po_metrics pm ON pm.supplier_id = s.id AND pm.org_id = s.org_id;

-- ============================================================================
-- RLS
-- ============================================================================
ALTER TABLE reorder_rules ENABLE ROW LEVEL SECURITY;
CREATE POLICY reorder_rules_tenant ON reorder_rules
  USING (org_id = tenant_org_id()) WITH CHECK (org_id = tenant_org_id());

ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY pos_tenant ON purchase_orders
  USING (org_id = tenant_org_id()) WITH CHECK (org_id = tenant_org_id());

ALTER TABLE purchase_order_lines ENABLE ROW LEVEL SECURITY;
CREATE POLICY po_lines_tenant ON purchase_order_lines
  USING (org_id = tenant_org_id()) WITH CHECK (org_id = tenant_org_id());

ALTER TABLE reorder_suggestions ENABLE ROW LEVEL SECURITY;
CREATE POLICY suggestions_tenant ON reorder_suggestions
  USING (org_id = tenant_org_id()) WITH CHECK (org_id = tenant_org_id());

ALTER TABLE webhooks ENABLE ROW LEVEL SECURITY;
CREATE POLICY webhooks_tenant ON webhooks
  USING (org_id = tenant_org_id()) WITH CHECK (org_id = tenant_org_id());

ALTER TABLE webhook_deliveries ENABLE ROW LEVEL SECURITY;
CREATE POLICY webhook_deliveries_tenant ON webhook_deliveries
  USING (org_id = tenant_org_id()) WITH CHECK (org_id = tenant_org_id());

-- ============================================================================
-- Permissions
-- ============================================================================
INSERT INTO permissions (code, name, description, category) VALUES
  ('purchase.po.approve', 'Approve / send POs', 'Send a draft purchase order to the supplier', 'Procurement'),
  ('purchase.webhook',    'Manage webhooks',    'Manage outbound webhook subscriptions', 'Procurement')
ON CONFLICT (code) DO NOTHING;

-- owner already inherits every permission code via the Phase 0 mapping, but
-- that mapping was seeded before these codes existed — add them explicitly.
INSERT INTO role_permissions (role_code, permission_code) VALUES
  ('owner',            'purchase.po.approve'),
  ('owner',            'purchase.webhook'),
  ('branch_manager',   'purchase.po.approve')
ON CONFLICT DO NOTHING;
